import smtplib
from email.mime.text import MIMEText

### Este archivo invoca a smtplib y define la funcion que envía mails

# Configuration
port = 2525
smtp_server = "sandbox.smtp.mailtrap.io"
login       = "9d7c8d6bcef763"             # Your login generated by Mailtrap
password    = "223a4381906a20"             # Your password generated by Mailtrap

def send_email(sender_email, receiver_email, subject, text):
    # Create MIMEText object
    message = MIMEText(text, "plain")
    message["Subject"] = subject
    message["From"]    = sender_email
    message["To"]      = receiver_email
    
    # Send the email
    with smtplib.SMTP(smtp_server, port) as server:
        server.starttls()  # Secure the connection
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message.as_string())
    
    print(header(f"\nMail sent\n"))